### ISSUE TITLE
Apple Vision Pro support

### ISSUE THREAD

**Issue by wzieba** [NotesTeam/TaskBook-iOS#1]
Hi there, thanks for the great app!

@justtwago I have a question: do you plan support for Apple Vision Pro?

**Comment by justtwago** [comment]
Thank you, @wzieba, for the kind words!
Since we value our users' experience, I propose waiting until the new technology is stable enough to integrate into the app.

**Comment by wzieba** [comment]
Thank you for the comprehensive answer. Please keep us updated, can't wait to add some tasks to TaskBook.

**Comment by justtwago** [comment]
Thank you for your suggestion, @wzieba. We do appreciate your interest in our product and invite you to follow up on the news on our [social media](https://www.instagram.com/dailyboberkurwa).
